### ISSUE TITLE
Google Maps won't open unless it has been open beforehand

### ISSUE THREAD

**Issue by daweido** [flexible-agency/react-native-map-link#156] opened 2020-11-24 18:28 UTC
Hello,

I'm creating this issue because I'm having some problem opening Google Maps on an Android phone when the application has not been opened before.

I'm rocking the styled popup. Upon choosing Google Maps, the native app chooser opens up, and then nothing happens.

However, if Google Maps is running (has been opened beforehand), then Google Maps App does open.

Has anyone had this issue and found a way to fix this?

Thanks!

**Comment by kukuandroid** [comment] 2020-11-25 00:38
Me too. im having this issue on ios 14.2 . Nothing happened, no error thrown

**Comment by kukuandroid** [comment] 2020-11-25 16:39
@daweido Hi, you found the solution ?

**Comment by daweido** [comment] 2020-11-25 16:42
@kukuandroid Unfortunately, not at all...

**Comment by daweido** [comment] 2020-11-25 19:05
ping @tschoffelen

**Comment by tschoffelen** [comment] 2020-12-18 15:55
Hmm, I can't reproduce this currently. Can I just clarify if this is happening on Android, iOS or both?

**Comment by daweido** [comment] 2020-12-18 17:00
Hi!

It was on Android where this bug happened.

**Comment by tschoffelen** [comment] 2020-12-18 22:25
We just changed something in the URL scheme for Google Maps on Android (see #158), maybe that has helped.

**Comment by tschoffelen** [comment] 2021-03-04 16:09
Closing this issue in favour of #138

**Closed by tschoffelen** 2021-03-04 16:09 UTC
