### ISSUE TITLE
How Can i stop auto directions in google maps

### ISSUE THREAD

**Issue by Kaung-Htet-Naing** [flexible-agency/react-native-map-link#194] opened 2021-08-24 07:24 UTC
![Screenshot_2021-08-24-17-10-42-194_com google android apps maps](https://user-images.githubusercontent.com/50987097/130603161-65105d1c-b830-4142-a432-77b1d960e81c.jpg)

When clicking google Maps, map is using directions and finding routes. How can I stop this ?

This is my Code !
` <Popup
          isVisible={isvisible}
          onCancelPressed={() => setIsVisible(false)}
          onAppPressed={() => setIsVisible(false)}
          onBackButtonPressed={() => setIsVisible(false)}
          options={{
            latitude: latlong.latitude,
            longitude: latlong.longitude,
            title: markerDetail.shop_name,
            dialogTitle: 'CUPLES',
            cancelText: 'Cancel'
          }}
          appsWhiteList={[]}
          modalProps={{
            animationIn: 'slideInUp'
          }}
        />`
@tschoffelen

**Comment by tschoffelen** [comment] 2021-09-19 09:39
Duplicate of #185 - if you can help with a PR that would be great!

Closing this issue so that we can continue the conversation in #185.

**Closed by tschoffelen** 2021-09-19 09:39 UTC
